// WebGPU JS FFI type definitions for MoonBit.

///|
pub type GPU

///|
pub type GPUAdapter

///|
pub type GPUDevice

///|
pub type GPUQueue

///|
pub type GPUCanvasContext

///|
pub type GPUTexture

///|
pub type GPUTextureView

///|
pub type GPUBuffer

///|
pub type GPUShaderModule

///|
pub impl @traits.WebGPUShaderModule for GPUShaderModule

///|
pub type GPURenderPipeline

///|
pub impl @traits.WebGPURenderPipeline for GPURenderPipeline

///|
pub type GPUCommandEncoder

///|
pub type GPURenderPassEncoder

///|
pub type GPUCommandBuffer

///|
pub impl @traits.WebGPUCommandBuffer for GPUCommandBuffer

///|
pub impl @traits.WebGPUTextureView for GPUTextureView

///|
pub type HTMLCanvasElement
