// WebGPU JS FFI type definitions for MoonBit.

///|
pub type GPU

///|
pub type GPUAdapter

///|
pub type GPUDevice

///|
pub type GPUQueue

///|
pub type GPUCanvasContext

///|
pub type GPUTexture

///|
pub type GPUTextureView

///|
pub type GPUShaderModule

///|
pub type GPURenderPipeline

///|
pub type GPUCommandEncoder

///|
pub type GPURenderPassEncoder

///|
pub type GPUCommandBuffer

///|
pub type GPUBuffer

///|
pub type GPUBindGroupLayout

///|
pub type GPUBindGroup

///|
pub type HTMLCanvasElement
